# Base image
FROM mysql

# Add a database
#ENV MYSQL_DATABASE website

# Add the SQL scripts to the image
# All scripts in /docker-entrypoint-initdb.d/ are automatically executed at container start
#COPY ./sqlscripts /docker-entrypoint-initdb.d/

# Expose the MySQL port, this may not be needed
EXPOSE 3306

